// documents/serviceArea.ts
export default {
  name: 'serviceArea',
  title: 'Service Area',
  type: 'document',
  fields: [
    { name: 'name',         type: 'string', title: 'City / Area Name',   validation: (R: any) => R.required() },
    { name: 'slug',         type: 'slug',   title: 'Slug',               options: { source: 'name' }, validation: (R: any) => R.required() },
    { name: 'county',       type: 'string', title: 'County' },
    { name: 'population',   type: 'number', title: 'Population (approx)' },
    {
      name: 'priority',
      type: 'string',
      title: 'Priority',
      options: {
        list: [
          { title: 'Primary',   value: 'primary' },
          { title: 'Secondary', value: 'secondary' },
          { title: 'Tertiary',  value: 'tertiary' },
        ],
        layout: 'radio',
      },
      initialValue: 'secondary',
      validation: (R: any) => R.required(),
    },
    { name: 'lat',          type: 'number', title: 'Latitude' },
    { name: 'lng',          type: 'number', title: 'Longitude' },
    { name: 'responseTime', type: 'string', title: 'Response Time (e.g. "30 minutes")' },
    { name: 'description',  type: 'text',   title: 'Area Description (1-2 sentences for area page)', rows: 3 },
    {
      name: 'zipCodes',
      type: 'array',
      title: 'ZIP Codes',
      of: [{ type: 'string' }],
    },
    {
      name: 'nearby',
      type: 'array',
      title: 'Nearby Areas',
      of: [{ type: 'reference', to: [{ type: 'serviceArea' }] }],
    },
    {
      name: 'localContext',
      title: 'Local Context (drives combo page copy)',
      type: 'object',
      description: 'Fill these in to generate unique, locally-aware content on service+area combo pages.',
      fields: [
        { name: 'propertyCharacter', type: 'text',   title: 'Property Character',    description: 'e.g. "mix of Victorian-era homes and postwar bungalows with steep hillside lots"', rows: 2 },
        { name: 'housingAge',        type: 'string', title: 'Housing Age',           description: 'e.g. "predominantly pre-1970 housing stock"' },
        { name: 'lotProfile',        type: 'string', title: 'Lot Profile',           description: 'e.g. "narrow urban lots" | "large rural acreage" | "flat suburban quarter-acres"' },
        { name: 'communityType',     type: 'string', title: 'Community Type',        description: 'e.g. "established residential neighborhood" | "fast-growing suburb"' },
        { name: 'demographics',      type: 'string', title: 'Resident Profile',      description: 'e.g. "mix of long-term homeowners and young families"' },
        { name: 'seasonalFactors',   type: 'text',   title: 'Seasonal Factors',      description: 'How local seasons affect service needs', rows: 2 },
        { name: 'permitNotes',       type: 'text',   title: 'Permit / Regulatory Notes', description: 'Any local permit requirements worth mentioning', rows: 2 },
        {
          name: 'notableFeatures',
          type: 'array',
          title: 'Notable Features',
          description: 'e.g. historic district, riverfront, active HOA, new construction',
          of: [{ type: 'string' }],
          options: { layout: 'tags' },
        },
        {
          name: 'commonChallenges',
          type: 'array',
          title: 'Common Service Challenges',
          description: 'Local conditions affecting work quality. e.g. "drainage issues from clay soil"',
          of: [{ type: 'string' }],
          options: { layout: 'tags' },
        },
        {
          name: 'landmarks',
          type: 'array',
          title: 'Local Landmarks',
          description: 'Well-known references that signal local familiarity',
          of: [{ type: 'string' }],
          options: { layout: 'tags' },
        },
        {
          name: 'neighboringAreas',
          type: 'array',
          title: 'Neighboring Areas',
          description: 'Adjacent neighborhoods used in copy to establish local knowledge',
          of: [{ type: 'string' }],
          options: { layout: 'tags' },
        },
      ],
    },
  ],
  orderings: [
    { title: 'Priority then Name', name: 'priorityName', by: [{ field: 'priority', direction: 'asc' }, { field: 'name', direction: 'asc' }] },
  ],
  preview: {
    select: { title: 'name', subtitle: 'county' },
  },
};
